version: '3.8'

services:
  roach1:
    image: cockroachdb/cockroach:latest-v23.2
    container_name: roach1
    command: >
      start --insecure
      --join=roach1:26257,roach2:26257,roach3:26257
    volumes:
      - roach1-data:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - roachnet

  roach2:
    image: cockroachdb/cockroach:latest-v23.2
    container_name: roach2
    command: >
      start --insecure
      --join=roach1:26257,roach2:26257,roach3:26257
    volumes:
      - roach2-data:/cockroach/cockroach-data
    networks:
      - roachnet

  roach3:
    image: cockroachdb/cockroach:latest-v23.2
    container_name: roach3
    command: >
      start --insecure
      --join=roach1:26257,roach2:26257,roach3:26257
    volumes:
      - roach3-data:/cockroach/cockroach-data
    networks:
      - roachnet

volumes:
  roach1-data:
  roach2-data:
  roach3-data:

networks:
  roachnet:
    driver: bridge